{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bulwark.fullname" . }}-config
  labels:
    {{- include "bulwark.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  {{- with .Values.persistence.config.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
{{- if and .Values.persistence.adminState.enabled (not .Values.persistence.adminState.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bulwark.fullname" . }}-admin-state
  labels:
    {{- include "bulwark.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.adminState.accessModes | nindent 4 }}
  {{- with .Values.persistence.adminState.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.adminState.size }}
{{- end }}
