{{- if and .Values.sessionSecret.value (not .Values.sessionSecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bulwark.sessionSecretName" . }}
  labels:
    {{- include "bulwark.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.sessionSecret.existingSecretKey }}: {{ .Values.sessionSecret.value | quote }}
{{- end }}
